paths:
  download_dir: download_tmp/
  test_dir: tmp/



force: True
case_id: "1"
all: False
start_case_id: "3962" # Only used when 'all' is True
messages:
  give_correct_input: >
    Please specify either a 'case_id'
    or use 'all' to scrape all cases.
  done: >
    Scraping done!
test_case_name: test_case
test_case_id: "1"

# Constants
sleep: 5
max_consecutive_nonexistent_page_count: 100
timeout_pdf_download: 20
