defaults:
  - _self_

hydra:
  run:
    dir: "."

domsdatabasen:
  url: https://domsdatabasen.dk/#sag

paths:
  download_dir: download_tmp/
  data_raw_dir: data/raw/
  data_processed_dir: data/processed/
  data_final_dir: data/final/
  test_dir: tmp/
  test_case_dir: test_case/

file_names:
  tabular_data: tabular_data.json
  pdf_document: document.pdf
  processed_data: processed_data.json
  dataset: dataset.jsonl

# Constants
## Scrape
sleep: 5
max_consecutive_nonexistent_page_count: 100

## Process
gpu: False

max_y_difference: 25

neighbor_distance_max: 1

box_area_min: 2000
box_height_min: 35
box_accept_ratio: 0.4
slight_shift_to_bottom: 5

threshold_binarize_anonymized_boxes: 1
threshold_binarize_refine_anonymized_box: 30
threshold_binarize_split_indices: 100
threshold_max_gap: 15


split_boxes_line_idx_shift: 8

underline_height_lower_bound: 1
underline_height_upper_bound: 7

max_expand_steps: 10

message_pdf_has_no_anonymized_boxes: >
  No anonymized boxes detected on first page 1.
  There will therefore not be searched for
  anonymized boxes on the following pages.
message_pdf_has_underline_anonymizations: >
  No underline anonymization detected on page 1.
  There will therefore not be searched for
  underlines anonymization on the following pages.
message_try_use_tika: >
  No anonymization found on page 1. 
  There will therefore be used to 
  read the text.
message_tika_failed: >
  Tika didn't work. 
  Easyocr will be used to read the text.



### Remove logo on first page
logo_row_idx: 500
logo_col_idx: 1500

# Testing
testing: False
test_case_name: test_case
test_case_id: "1"

# Scrape arguments
scrape:
  force: False
  case_id: "1"
  all: False
  messages:
    give_correct_input: >
      Please specify either a 'case_id'
      or use 'all' to scrape all cases.
    done: >
      Scraping done!

# Process arguments
process:
  force: True
  case_id: "3"
  all: False
  messages:
    give_correct_input: >
      Please specify either a 'case_id'
      or use 'all' to process all cases.
    done: >
      Processing done!

# Finalize arguments
finalize:
  force: False