defaults:
  - scrape: scrape
  - process: process
  - finalize: finalize
  - _self_

hydra:
  run:
    dir: "."

domsdatabasen:
  url: https://domsdatabasen.dk/#sag

paths:
  hf_hub: alexandrainst/domsdatabasen
  data_raw_dir: data/raw/
  data_processed_dir: data/processed
  data_final_dir: data/final

file_names:
  tabular_data: tabular_data.json
  pdf_document: document.pdf
  processed_data: processed_data.json
  dataset: dataset.jsonl

# Anonymization method
anon_method:
  underline: underline
  box: box
  none: none

testing: False
