defaults:
  - scrape: scrape
  - process: process
  - _self_

hydra:
  run:
    dir: "."

domsdatabasen:
  url: https://domsdatabasen.dk/#sag


paths:
  hf_hub: oliverkinch/domsdatabasen
  data_raw_dir: data/raw/
  data_processed_dir: /mnt/data_6tb/oliver/doms_databasen/data/processed
  data_final_dir: /mnt/data_6tb/oliver/doms_databasen/data/final

file_names:
  tabular_data: tabular_data.json
  pdf_document: document.pdf
  processed_data: processed_data.json
  dataset: dataset.jsonl

# Anonymization method
anon_method:
  underline: underline
  box: box
  none: none


message_pdf_has_no_anonymized_boxes: >
  No anonymized boxes detected on first page 1.
  Therefore, there will not be searched for
  anonymized boxes on the following pages.
message_pdf_has_no_underline_anonymizations: >
  No underline anonymization detected on page 1.
  Therefore, there will not be searched for
  underlines anonymization on the following pages.

message_case_not_found: >
  The case was not found. 
  Case id:
message_case_already_processed: >
  The case has already been processed. Use 'process.force' to overwrite
  Case id:
message_processing_case: >
  Processing case:
message_case_done: >
  Done with case:
message_processing_all_cases: >
  Processing all cases.

testing: False


## Debug
image_idx: False # page number

# Finalize arguments
finalize:
  force: False