defaults:
  - _self_

hydra:
  run:
    dir: "."

domsdatabasen:
  url: https://domsdatabasen.dk/#sag

paths:
  download_dir: download_tmp/
  data_raw_dir: data/raw/
  test_dir: tmp/
  test_case_dir: test_case/

file_names:
  tabular_data: tabular_data.json
  pdf_document: document.pdf

messages:
  give_correct_inputs: >
    Please specify either a case ID using the case_id 
    argument or use --scrape_all to scrape all cases

sleep: 5
testing: False
test_case_name: test_case

# Arguments
force: False
case_id: "1"
scrape_all: False
