defaults:
  - _self_

hydra:
  run:
    dir: "."

domsdatabasen:
  url: https://domsdatabasen.dk/#sag

paths:
  download_dir: download_tmp/
  data_raw_dir: data/raw/
  data_processed_dir: data/processed/
  data_final_dir: data/final/
  test_dir: tmp/
  test_case_dir: test_case/

file_names:
  tabular_data: tabular_data.json
  pdf_document: document.pdf
  processed_data: processed_data.json
  dataset: dataset.jsonl

# Constants
sleep: 5
n_files_raw_case_dir: 2
n_files_processed_case_dir: 1
max_consecutive_nonexistent_page_count: 100
max_y_difference: 25
gpu: False
dpi: 300
min_bbox_area: 2000
truncate_image_top: 100 # Top and bottom of page
truncate_image_bottom: 75

# Testing
testing: False
test_case_name: test_case
test_case_id: "1"

# Scrape arguments
scrape:
  force: False
  case_id: "1"
  all: False
  messages:
    give_correct_input: >
      Please specify either a 'case_id'
      or use 'all' to scrape all cases.
    done: >
      Scraping done!

# Process arguments
process:
  force: True
  case_id: "2350"
  all: False
  messages:
    give_correct_input: >
      Please specify either a 'case_id'
      or use 'all' to process all cases.
    done: >
      Processing done!

# Finalize arguments
finalize:
  force: False