name: CI

on:
  pull_request:
    branches:
      - master

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jpetrucciani/black-check@23.12.0

  pytest:
    strategy:
        matrix:
            os: [ubuntu-latest]
            python-version: ["3.11"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install Dependencies
        run: |
          poetry env use "${{ matrix.python-version }}"
          poetry install --extras all

      - name: Test with pytest
        run: make test
