name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jpetrucciani/black-check@23.12.0

  pytest:
    strategy:
        matrix:
            os: [ubuntu-latest]
            python-version: ["3.10"]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install Dependencies
        run: |
          poetry env use "${{ matrix.python-version }}"
          poetry install --all-extras
          
      - name: Install poppler-utils
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Test with pytest
        run: poetry run make test
